### ISSUE TITLE
Is there any standard for epub Cover image?

### ISSUE THREAD

**Issue by einverne** [aerkalov/ebooklib#171]
I have noticed that this lib use this judge to get epub cover information

    if 'cover-image' in properties:

However, I found most of the epub files I have, I cannot get the EpubCover by using

    book.get_items_of_type(ebooklib.ITEM_COVER)

I have search for quite a while, and I haven't found any useful information about the cover standard. So according to my knowledge, I have change this code as following in order to get cover Image each time.

    if 'cover-image' in properties or 'cover.jpg' in r.get('id'):

- <http://idpf.org/epub/31>

**Comment by aerkalov** [comment]
Yeah, parsing random EPUB files can be an issue. 'cover-image' in properties is defined by the specification and that is what library does. But for the custom implementation it would be better to have extra checks like you did. I would probably do something like ```'cover' in r.get('id').lower()```, just because people like to put capital letters and not always put extension inside. Also, as I recall couple of years ago when I was doing some custom code for certain publishers I also had to add extra meta information, like it is defined here - http://idpf.org/forum/topic-715 so if you are parsing random EPUB files it would be wise to check for that extra meta info also.

**Comment by balconyRewrap** [comment]
Hello, will this be solved in 1.0? The issue has been closed for a long time, but the current codebase still contains this problem related to the cover.

**Comment by c1924959470** [comment]
您好！您的来信我已接受，我会尽快回复您。
