### ISSUE TITLE
Update an epub file

### ISSUE THREAD

**Issue by dr-nyt** [aerkalov/ebooklib#189]
Hey!
I was wondering if it was possible to update a pre-existing epub file by adding more sections/chapters to it.

**Comment by dr-nyt** [comment]
I can't find any docs on how to get each chapter from a pre-generated epub. book.get_items(), can't seem to figure out what parameters for getting the chapters.

**Comment by dr-nyt** [comment]
Now, this is stupid, but right after I posted, I found one of your documented pdfs online sigh... You should probably link this in the README aswell https://readthedocs.org/projects/ebooklib/downloads/pdf/latest/

**Comment by dr-nyt** [comment]
One last issue, I have the chapter object but can't seem to get the title of the chapter from it like i can with its content
for chapter in book.get_items_of_type(ebooklib.ITEM_DOCUMENT):
    print(chapter.get_content())    #works
    print(chapter.get_metadata('DC', 'title'))    #doesn't work
    print(chapter.get_title())    #doesn't work

**Comment by aerkalov** [comment]
Yeah, it is missing that feature. This is mainly because the original idea was to read EPUB, create new EPUB object and pass only things you need. But to be honest no reason why title, language or something else would not work with that idea in mind.

To make it work now you need to get the content and parse the <title> yourself at the moment.  Same thing with language and links defined in the chapter. They are not "parsed" when epub is read.

**Comment by dr-nyt** [comment]
Thanks I did just that! Appreciate your time :blush:
